config/routes.rb
Rails.application.routes.draw do
  resources :people, only: [:new, :create, :show, :edit, :update]

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_attributes)
    if @person.save
      redirect_to @person, notice: "Person created."
    else
      render :new
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_attributes)
      redirect_to @person, notice: "Person updated."
    else
      render :edit
    end
  end

  private

  def person_attributes
    params.require(:person).permit(:first_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingFundamentalsWriteAnIntegrationTest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/people/edit.html.erb
<%= form_for @person do |form| %>
  <%= @person.errors.full_messages %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
  <%= form.submit %>
<% end %>

app/views/people/new.html.erb
<%= form_for @person do |form| %>
  <%= @person.errors.full_messages %>
  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
  <%= form.submit "Create Person" %>
<% end %>

app/views/people/show.html.erb
<%= @person.first_name %>
<%= link_to "Edit", edit_person_path(@person) %>